### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by teaey** [jonfhancock/JsonToJava#7]
```
Created PublicIpAddress.java
Created InnerIpAddress.java
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
    at com.jsontojava.Member.getGetterSignature(Member.java:104)
    at com.jsontojava.Member.getGetter(Member.java:125)
    at com.jsontojava.NewType.toString(NewType.java:128)
    at com.jsontojava.Main.main(Main.java:90)
```

**Comment by teaey** [comment]
Okay. I just use http://jsontojava.appspot.com/ to generate. It's fine.
